// Code generated by "stringer -type=ContentEncoding"; DO NOT EDIT.

package http_ece

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AES128GCM-1]
	_ = x[AESGCM-2]
}

const _ContentEncoding_name = "AES128GCMAESGCM"

var _ContentEncoding_index = [...]uint8{0, 9, 15}

func (i ContentEncoding) String() string {
	i -= 1
	if i < 0 || i >= ContentEncoding(len(_ContentEncoding_index)-1) {
		return "ContentEncoding(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ContentEncoding_name[_ContentEncoding_index[i]:_ContentEncoding_index[i+1]]
}
